from rsf.tex import *
import os, sys
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5 serifs=n'

env=Environment()
if sys.platform == 'darwin':
    env['ENV']['PATH'] = ':'.join(['/opt/local/bin',env['ENV']['PATH']])


# for revised paper
Paper('topic_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath,listings')
Command('topic_revise_plain1.tex','topic_revise1.tex','cp $SOURCE $TARGET')
Paper('topic_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath')

# for reply letter
Paper('reply1',use='hyperref,listings')

# for a common seg abstract
Paper('seg2015_enhemd',lclass='segabs',use='amsmath,listings')

# for seg abstract, without reference page
env.Command('seg2015_enhemd_final.pdf','seg2015_enhemd_final.ltx','pdflatex $SOURCE')

# for a common eage abstract
Paper('enhemdeage',lclass='mad15',use='listings, amsmath,subfigure') 
Paper('enhemd',lclass='geophysics',options='manuscript',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')
          
Paper('enhemd_revise1',lclass='geophysics',options='manuscript,revised',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')
          
Command('enhemd_revise_plain1.tex','enhemd_revise1.tex','cp $SOURCE $TARGET')
Paper('enhemd_revise_plain1',lclass='geophysics',options='manuscript',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')  
Paper('reply1',use='hyperref,listings')               
          
Paper('enhemd_revise2',lclass='geophysics',options='manuscript,revised',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')
          
Command('enhemd_revise_plain2.tex','enhemd_revise2.tex','cp $SOURCE $TARGET')
Paper('enhemd_revise_plain2',lclass='geophysics',options='manuscript',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')  
Paper('reply2',use='hyperref,listings')           



## Make sure there is a firstbreak.bst in your directory

# For slides
Paper('slides',lclass='beamer',use='amsmath,amsbsy,listings,overpic,color,multicol,amssymb,comment,verbatim', include=r'''
      \mode<presentation>{\usetheme{AnnArbor}}
      \mode<presentation>{\usecolortheme{beaver}}
      \newcommand{\TEXMF}{%s/texmf}
      ''' % os.environ.get('HOME'))

# For default paper.tex
End(use='amsmath,listings')
