#! /bin/sh
# Homomorphic wavelet estimator

indata=seis_shot_101.su
outdata=wavelet_est.su

# stack real part of the complex log transform (log|A|)
suclogfft < $indata  | suamp mode=real | sustack key=dt > real.su

# stack imaginary part of the complex log transform (phase)
suclogfft < $indata  | suamp mode=imag | sustack key=dt > imag.su

# combine real and imag and inverse clog transform

suop2 real.su imag.su op=zipper | suiclogfft  | suminphase  |
suwind itmax=199 > $outdata

# compare with farfield_gun.su
cat farfield_gun.su $outdata | suxwigb


exit 0


suaddevent < pegleg1.1sec.su type=nmo nt=1500 t0=2.5  dt=.004 vel=2000 |
suaddevent type=nmo nt=1500 t0=3.0  dt=.004 vel=1950 |
suaddevent type=nmo nt=1500 t0=3.5  dt=.004 vel=1900 |
suaddevent type=nmo nt=1500 t0=4.0  dt=.004 vel=1850 |
suaddevent type=nmo nt=1500 t0=4.5  dt=.004 vel=1800 |
suaddevent type=nmo nt=1500 t0=5.0  dt=.004 vel=1750 |
suaddevent type=nmo nt=1500 t0=5.5  dt=.004 vel=1700  \
> pegleg1.1+2.0sec.su


suaddevent <  pegleg1.1+2.0sec.su type=nmo nt=1500 t0=3.8  dt=.004 vel=2400 |
suaddevent type=nmo nt=1500 t0=4.3  dt=.004 vel=2350 |
suaddevent type=nmo nt=1500 t0=4.8  dt=.004 vel=2300 |
suaddevent type=nmo nt=1500 t0=5.1  dt=.004 vel=2250 |
suaddevent type=nmo nt=1500 t0=5.6  dt=.004 vel=2200 \
> pegleg1.1+2.0+3.3sec.su

cp pegleg1.1+2.0+3.3sec.su pegleg.su

susum fake.su waterbottom.su > fake+water.su

susum  fake+water.su pegleg.su > fake+water+pegleg.su


exit 0

