#! /bin/sh

nxo=2142
nxshot=1012
nz=1500
dz=3
dx=12.5
vfile=unewvelxz.bin
fmax=90

data=sigdecon_radon_mute_seis_repaired_shot.su

susort sx offset <  $data > data.shot.su

sumigpreffd < data.shot.su nxo=$nxo nxshot=$nxshot nz=$nz dz=$dz dx=$dx fmax=$fmax vfile=$vfile verbose=1 > pre_ffd.su


exit 0

