from rsf.proj import*
import math 


def grey(title):
    return 'grey title="%s" label2=Channel label1="Time (s)" ' % title
mute='mutter hyper=y half=y t0=1.8 x0=0 slope0=0.005 | mutter hyper=n half=y t0=2.1 x0=0 slope0=0.002'


def Graph(data,other):
	Result(data,'graph label1="Time" label2="Amplitude" unit2= unit1="s" labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title="" wherexlabel=b wheretitle=t screenratio=0.5 %s' %other)
	
## module definition
def Grey(data,other): 
	Result(data,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=b wheretitle=t screenratio=1.4 color=g %s'%other)

def Greyplot(data,other): 
	Plot(data,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=b wheretitle=t labelsz=10  color=g %s'%other)
	
Flow('sean1','sean.HH',
     'dd form=native | window n2=1 f2=10 | put o2=0 d2=10 ')

Flow('sean2','sean.HH',
     'dd form=native | window n2=1 f2=9 | put o2=0 d2=10 ')

Flow('sean3','sean.HH',
     'dd form=native | window n2=1 f2=8| put o2=0 d2=10 ')

Flow('sean4','sean.HH',
     'dd form=native | window n2=1 f2=20| put o2=0 d2=10 ')


# a unblended
# b blended
# c deblended (fk)
# d deblended (proposed)                    
Greyplot('sean1','title="(a)"')    
Greyplot('sean2','title="(b)" wantaxis1=n') 
Greyplot('sean3','title="(c)" wantaxis1=n')
Greyplot('sean4','title="(d)" wantaxis1=n') 
Result('sean','sean1 sean2 sean3 sean4','SideBySideAniso',vppen='txscale=2')   

#trace comparison
Flow('s1','sean1','window n2=1 f2=4')
Flow('s2','sean1','window n2=1 f2=3')
Flow('s3','sean1','window n2=1 f2=2')


Flow('ss','s1 s2 s3','cat axis=2 ${SOURCES[1:3]}')
Graph('ss','plotfat=10 plotcol="7,3,5"') #7,3,5,4,6

  
End()
