#! /bin/sh
# example of using susvdfilt to remove linear noise (direct wave) from data
#
#
# create example gather with combined hyperbolic events and linear event for water column (v=1500 m/s) with some noise.
# The direct wave has an decreasing amplitude with offset, but the reflection events do not

sunull nt=1000 dt=0.002 ntr=120 | sushw key=offset a=0 b=20 | suaddevent vel=1500 amp=10 t0=0.05 type=lmo | suweight inv=1 b=0.01 | suaddevent vel=1500 t0=0.8 | suaddevent vel=1500 t0=0.4 amp=-0.5 | suaddnoise sn=200 | sufilter f=8,12,40,60 > raw.su

##add delay to data, run svd to remove linear event, then remove delay

sushw key=delrt a=500 < raw.su | sushift tmin=0 tmax=2.5 | sureduce rv=1.5 | susvdfilt numpp=1 | suflip flip=3 | sureduce rv=1.5 | suflip flip=3 | sushw key=delrt a=-500 | sushift tmin=0 tmax=2 > filtered.su

## and again but this time extracting the linear event
sushw key=delrt a=500 < raw.su | sushift tmin=0 tmax=2.5 | sureduce rv=1.5 | susvdfilt numpp=1 subtract=0 | suflip flip=3 | sureduce rv=1.5 | suflip flip=3 | sushw key=delrt a=-500 | sushift tmin=0 tmax=2 > direct.su


## plot
supswigb title="original" nbpi=100 clip=0.1 < raw.su > raw.ps
supswigb title="filtered" nbpi=100 clip=0.1 < filtered.su > filtered.ps
supswigb title="direct" nbpi=100 clip=0.1 < direct.su > direct.ps

echo "Open the file: raw.ps with your PS viewer" &
echo "Open the file: filtered.ps with your PS viewer" &
echo "Open the file: direct.ps" &


exit 0
