from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi

# Data size: 301*61*61

def Grey3(data,other):
	Result(data,
       '''
       byte clip=0.3 |
       grey3 flat=n frame1=100 frame2=5 frame3=5 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=
       screenratio=1.4 color=g %s'''%other)

def Grey32(data,other):
	Result(data,
       '''
       byte clip=0.27 |
       grey3 flat=n frame1=100 frame2=5 frame3=5 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=
       screenratio=1.4 color=g %s'''%other)

def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.3 title=
       screenratio=1.4 color=g color=g %s'''%other)

## Load data

Flow('field-noisy','../data/field_noisy.bin','bin2rsf bfile=${SOURCES[0]} n1=300 n2=1600 | put n2=100 n3=16 d1=0.004 d2=1 d3=1 o1=1 o2=1 o3=1')
Flow('field-obs','../data/field_obs.bin','bin2rsf bfile=${SOURCES[0]} n1=300 n2=1600 | put n2=100 n3=16 d1=0.004 d2=1 d3=1 o1=1 o2=1 o3=1')
Flow('field-mssa','../data/field_mssa.bin','bin2rsf bfile=${SOURCES[0]} n1=300 n2=1600 | put n2=100 n3=16 d1=0.004 d2=1 d3=1 o1=1 o2=1 o3=1')
Flow('field-dmssa','../data/field_dmssa.bin','bin2rsf bfile=${SOURCES[0]} n1=300 n2=1600 | put n2=100 n3=16 d1=0.004 d2=1 d3=1 o1=1 o2=1 o3=1')



Grey3('field-noisy','title=Noisy')
Grey3('field-obs','title=Observed')
Grey3('field-mssa','title=MSSA')
Grey32('field-dmssa','title="Proposed (K=3)"')


# Xline=4

Flow('field-s-noisy','field-noisy','window n3=1 f3=4')
Flow('field-s-obs','field-obs','window n3=1 f3=4')
Flow('field-s-mssa','field-mssa','window n3=1 f3=4')
Flow('field-s-dmssa','field-dmssa','window n3=1 f3=4')

Grey('field-s-noisy','title=Noisy')
Grey('field-s-obs','title=Observed')
Grey('field-s-mssa','title=MSSA')
Grey('field-s-dmssa','title="Proposed (K=3)" clip=0.27')






End()
