from rsf.tex import*
env=Environment()
if sys.platform == 'darwin':
    env['ENV']['PATH'] = ':'.join(['/opt/local/bin',env['ENV']['PATH']])
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5'

#Paper('seg',lclass='geophysics',use='amsmath')
Paper('seg',lclass='geophysics',options='manuscript',use='amsmath')
Paper('emdseis',lclass='geophysics',options='manuscript',use='natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')  

Paper('emdseiseage',lclass='mad15',use='amsmath,subfigure')

Paper('emdseisjse',lclass='geophysics',options='manuscript',use='amsmath,subfigure')
Paper('gji',lclass='geophysics',options='manuscript',use='amsmath,subfigure')

#Paper('emdseis',lclass='geophysics',use='amsmath')

#Paper('seg',lclass='segabs',use='amsmath')




Paper('emdseis_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('emdseis_revise_plain1.tex','emdseis_revise1.tex','cp $SOURCE $TARGET')
Paper('emdseis_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath') 
Paper('reply1',use='hyperref,listings')   

Paper('emdseis_revise2',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('emdseis_revise_plain2.tex','emdseis_revise2.tex','cp $SOURCE $TARGET')
Paper('emdseis_revise_plain2',lclass='geophysics',options='manuscript',use='amsmath') 
Paper('reply2',use='hyperref,listings')  

Paper('emdseis_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('emdseis_revise_plain1.tex','emdseis_revise1.tex','cp $SOURCE $TARGET')
Paper('emdseis_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath') 
Paper('reply1',use='hyperref,listings')   

Paper('emdseis_revise3',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('emdseis_revise_plain3.tex','emdseis_revise3.tex','cp $SOURCE $TARGET')
Paper('emdseis_revise_plain3',lclass='geophysics',options='manuscript',use='amsmath') 
Paper('reply3',use='hyperref,listings')  

Paper('seg2015_dipsep',lclass='segabs',use='listings, amsmath,subfigure')
env.Command('seg2015_dipsep_final.pdf','seg2015_dipsep_final.tex','pdflatex $SOURCE')









Paper('emd_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('emd_revise_plain1.tex','emd_revise1.tex','cp $SOURCE $TARGET')
Paper('emd_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath') 



Paper('gji_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('gji_revise_plain1.tex','gji_revise1.tex','cp $SOURCE $TARGET')
Paper('gji_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath') 

Paper('gji_revise2',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('gji_revise_plain2.tex','gji_revise2.tex','cp $SOURCE $TARGET')
Paper('gji_revise_plain2',lclass='geophysics',options='manuscript',use='amsmath') 


Paper('r1',use='hyperref,listings')   
End(use='listings,amsmath')
